### ISSUE TITLE
[Styling] Centered content and better text contrast ?

### ISSUE THREAD

**Issue by NgyAnthony** [sodadata/docs#138]
Hi there, I discovered your tool from one of your business dev on LinkedIn and started reading your docs and I have a few suggestions.

IMO the text lacks contrast, particularly in the code samples. It's a bit difficult to read, the comments have more contrast than the actual code.
WebAIM: https://webaim.org/resources/contrastchecker/?fcolor=93A1A1&bcolor=8B9092

I also recommend centering the contents, it's better to not have to tilt your head left to read.

Internally we use https://docusaurus.io/, if that helps.

**Comment by janet-can** [comment]
Hey @NgyAnthony, thanks so much for your feedback. In truth, I had been sort of waiting for your comment about contrast because I tend to agree; I think we need to make some adjustments there to improve the contrast. I'll try changing it to see what it looks like.
Regarding the centering of contents, I believe we constrained to the left to favor a mobile experience, I think? But I see your point. Maybe there's a way to ease that constraint for a better desktop experience. 

Thanks again for your comments!
