### ISSUE TITLE
Data type usecase example

### ISSUE THREAD

**Issue by ViktorDronov** [sodadata/docs#451]
Our dataset used columns in a type `Decimal(7, 2)`
In a documentation there declared that [type](https://docs.soda.io/soda/connect-spark.html#supported-data-types) but there no examples hove to use that

Same with other links, like [this](https://docs.soda.io/soda-cl/validity-metrics.html#list-of-valid-formats)

**Comment by janet-can** [comment]
Hi @ViktorDronov, 
Thanks for bringing this up. It was a decision on purpose to not put all the detailed data types in the table on the numeric metrics page so that the table itself would not be overwhelmingly crowded. The more granular data type details are available on each data sources page.
Please re-open this ticket if I have misunderstood your request!
