### ISSUE TITLE
Missing metrics documentation question

### ISSUE THREAD

**Issue by hankowens** [sodadata/docs#693]
Section on define-checks-with-missing-metrics is confusing. Should the first check be `missing_count(phone) < 5`? Why is one `5%` and the other `5`?  
Maybe i just can't think of an example where you would want 5% of rows missing but NOT 4.9% or 5.1%. Either way that wouldnt be a "threshold." 
```
checks for dim_reseller:
# a check with a fixed threshold
  - missing_percent(phone) = 5%
# a check with a relative threshold
  - missing_percent(number_employees) < 5
```
https://docs.soda.io/soda-cl/missing-metrics.html#define-checks-with-missing-metrics

**Comment by janet-can** [comment]
Heh, your point is taken about the `=` threshold. That is an oddity-- I think I originally had a `0` value there and just didn't change the comparison operator. I ought to adjust that.
Meanwhile, for the `%` sign: the character is optional,  something I aimed to cleverly demonstrate in the examples but it comes off as a distraction rather than a demonstration of what is possible. Not good. I think I'll add the `%` to both.
Thanks for your feedback, @hankowens!
